### ISSUE TITLE
Allow dynamically changing the list of containers watched

### ISSUE THREAD

**Issue by rmartinho** [cpuguy83/docker-grand-ambassador#9]
It would be nice I could say run something like `docker exec -t ambassador_container grand-ambassador -watch new_container` or `docker exec -t ambassador_container grand-ambassador -unwatch old_container` to watch new containers or stop watching old ones without having to restart the ambassador with different `-name` flags.

**Comment by cpuguy83** [comment]
Generally I'd recommend only watching 1 container per ambassador and use consistent names for your containers which are the same (e.g. you've upgraded mysql to a new version, use the same name as the old container).

Closing since this is really out of scope for the project, and generally not going to be needed in the future with Docker's experimental networks/services functionality.

**Comment by ryneeverett** [comment]
> Generally I'd recommend only watching 1 container per ambassador and use consistent names for your containers which are the same (e.g. you've upgraded mysql to a new version, use the same name as the old container).

I came to the same conclusion after trial and error. It might be good to document this suggestion.
